import XCTest
@testable import FlowPeekCore

/// The markers were added after a bug report: with a diagram on the clipboard, dragging over
/// ordinary text on a web page raised the badge again and again. OpenClip, a PopClip-style utility,
/// borrows the clipboard to read the selection and puts the old contents back, and the restore is
/// what the badge was announcing. These are the types that restore carried.
final class PasteboardMarkersTests: XCTestCase {
    /// The exact type list read off the general pasteboard while the bug was reproducing.
    private static let restoredByAUtility = [
        "public.utf8-plain-text",
        "NSStringPboardType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    func testAnOrdinaryCopyIsAUserCopy() {
        XCTAssertTrue(PasteboardMarkers.isUserCopy(types: ["public.utf8-plain-text", "NSStringPboardType"]))
        XCTAssertTrue(PasteboardMarkers.isUserCopy(types: []))
        // A type that merely mentions the convention's prefix is not one of its markers.
        XCTAssertTrue(PasteboardMarkers.isUserCopy(types: ["org.nspasteboard.SomethingElse"]))
    }

    func testTheRestoreThatCausedTheBugIsNotAUserCopy() {
        XCTAssertFalse(PasteboardMarkers.isUserCopy(types: Self.restoredByAUtility))
        XCTAssertEqual(
            PasteboardMarkers.markers(in: Self.restoredByAUtility),
            [PasteboardMarkers.transient, PasteboardMarkers.autoGenerated]
        )
    }

    /// Either marker on its own is enough. A utility that sets one and not the other is still not
    /// speaking for the user.
    func testEitherMarkerAloneIsEnough() {
        XCTAssertFalse(PasteboardMarkers.isUserCopy(types: ["public.utf8-plain-text", PasteboardMarkers.transient]))
        XCTAssertFalse(PasteboardMarkers.isUserCopy(types: ["public.utf8-plain-text", PasteboardMarkers.autoGenerated]))
    }

    /// A password manager's write. This one is not about the badge: concealed content is not to be
    /// read at all, and the check happens before the string is fetched.
    func testConcealedContentIsNotAUserCopy() {
        XCTAssertFalse(PasteboardMarkers.isUserCopy(types: ["public.utf8-plain-text", PasteboardMarkers.concealed]))
        XCTAssertEqual(PasteboardMarkers.markers(in: ["public.utf8-plain-text", PasteboardMarkers.concealed]),
                       [PasteboardMarkers.concealed])
    }
}
