/// The pasteboard types an application uses to say something about the write itself rather than
/// about its content.
///
/// These are the conventions at nspasteboard.org, and the reason this file exists is a bug report:
/// with a diagram on the clipboard, dragging over any ordinary text on a web page raised the badge
/// again, over and over. Measured on the machine it was reported from, every drag moved the general
/// pasteboard's change count by two while its content stayed byte for byte the same diagram:
///
///     changeCount 1398 -> 1400   front=com.google.Chrome
///     types: public.utf8-plain-text, NSStringPboardType,
///            org.nspasteboard.TransientType, org.nspasteboard.AutoGeneratedType
///
/// Two writes, because a utility that reads the selection borrows the clipboard to do it and puts
/// the old contents back afterwards. The restore is not a copy anybody made, and it says so in the
/// only way the platform offers: by marking the write transient and auto-generated. A watcher that
/// looks only at the change count cannot tell that from the real thing, which is what made the
/// badge appear on a drag.
///
/// `Concealed` is here for a different reason and matters more. A password manager marks what it
/// puts on the clipboard with it, and nothing that reads clipboards should so much as look at that
/// content. FlowPeek would only have ignored it anyway -- a password does not parse as a diagram --
/// but "we would not have understood it" is not the same as not reading it.
public enum PasteboardMarkers {
    /// Written to be pasted once and forgotten; a clipboard history should not keep it.
    public static let transient = "org.nspasteboard.TransientType"
    /// Written by software rather than by a person asking for it.
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// A secret. Not to be read, stored, or looked at.
    public static let concealed = "org.nspasteboard.ConcealedType"

    /// Every marker that means "this write does not speak for the user".
    public static let all = [transient, autoGenerated, concealed]

    /// Whether this write is a copy a person made, and so worth announcing.
    ///
    /// Anything unmarked is, which is almost every copy there is: these types are opt-in, and an
    /// application that says nothing is treated exactly as it was before.
    public static func isUserCopy(types: [String]) -> Bool {
        !types.contains { all.contains($0) }
    }

    /// Which markers a write carries, for saying in a log why it was passed over. The content is
    /// never logged; the marker is not content.
    public static func markers(in types: [String]) -> [String] {
        all.filter { types.contains($0) }
    }
}
