import AppKit
import FlowPeekCore
import XCTest

@testable import FlowPeek

/// The watcher against a pasteboard of its own, driven the way the reported bug drove the real one.
///
/// OpenClip, a PopClip-style utility, reads the selection by borrowing the clipboard and putting the
/// old contents back. Measured while the bug reproduced: every drag over ordinary text moved the
/// general pasteboard's change count by two, left the same diagram on it, and marked the write
/// `org.nspasteboard.TransientType` and `org.nspasteboard.AutoGeneratedType`. The badge announced
/// each of those as a fresh copy.
@MainActor
final class ClipboardMarkerTests: XCTestCase {
    private static let diagram = "graph TD\n    A[\"start\"] --> B[\"end\"]\n"

    /// A pasteboard nobody else writes to, so a case cannot be disturbed by the machine's clipboard
    /// and cannot disturb it either.
    private func makePasteboard(_ function: String = #function) -> NSPasteboard {
        let board = NSPasteboard(name: NSPasteboard.Name("com.selenehyun.FlowPeek.test.\(function)"))
        board.clearContents()
        return board
    }

    private func write(_ text: String, to board: NSPasteboard, markers: [String] = []) {
        board.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for marker in markers { item.setString("", forType: NSPasteboard.PasteboardType(marker)) }
        board.writeObjects([item])
    }

    private func announcements(from board: NSPasteboard, _ steps: () -> Void) -> [String] {
        let monitor = ClipboardMonitor(pasteboard: board)
        var seen: [String] = []
        monitor.onMermaidCopied = { seen.append($0.text) }
        self.monitor = monitor
        steps()
        return seen
    }

    /// Held so the closure above outlives the call.
    private var monitor: ClipboardMonitor?

    /// The bug. A copy the user made is announced; the utility putting that same text back is not,
    /// however many times it does it.
    func testARestoredClipboardIsNotAnnouncedAgain() {
        let board = makePasteboard()
        let monitor = ClipboardMonitor(pasteboard: board)
        var seen: [String] = []
        monitor.onMermaidCopied = { seen.append($0.text) }

        write(Self.diagram, to: board)
        monitor.poll()
        XCTAssertEqual(seen.count, 1, "the copy the user made is the one worth announcing")

        for _ in 0..<5 {
            write(Self.diagram, to: board, markers: [PasteboardMarkers.transient, PasteboardMarkers.autoGenerated])
            monitor.poll()
        }
        XCTAssertEqual(seen.count, 1, "five restores after it announced nothing")
    }

    /// The markers are honoured on their own, before the content is looked at: a diagram FlowPeek
    /// has never seen, written by software, is still not a copy anybody made.
    func testAMarkedWriteIsPassedOverEvenWhenItIsNew() {
        let board = makePasteboard()
        let monitor = ClipboardMonitor(pasteboard: board)
        var seen: [String] = []
        monitor.onMermaidCopied = { seen.append($0.text) }

        write("sequenceDiagram\n    A->>B: hello\n", to: board, markers: [PasteboardMarkers.autoGenerated])
        monitor.poll()
        XCTAssertTrue(seen.isEmpty)
    }

    /// And the guard behind the markers, for a utility that restores without marking anything: the
    /// change count moves, the text does not, and nothing is announced twice.
    func testAnUnmarkedRepeatOfTheSameTextIsPassedOver() {
        let board = makePasteboard()
        let monitor = ClipboardMonitor(pasteboard: board)
        var seen: [String] = []
        monitor.onMermaidCopied = { seen.append($0.text) }

        write(Self.diagram, to: board)
        monitor.poll()
        write(Self.diagram, to: board)
        monitor.poll()
        XCTAssertEqual(seen.count, 1)
    }

    /// Copying the diagram again after copying something else is a real second copy, and it is
    /// announced. This is why the watcher remembers every write it reads rather than the last one
    /// it announced.
    func testCopyingItAgainAfterSomethingElseIsANewCopy() {
        let board = makePasteboard()
        let monitor = ClipboardMonitor(pasteboard: board)
        var seen: [String] = []
        monitor.onMermaidCopied = { seen.append($0.text) }

        write(Self.diagram, to: board)
        monitor.poll()
        write("a shopping list, no diagram in sight", to: board)
        monitor.poll()
        write(Self.diagram, to: board)
        monitor.poll()
        XCTAssertEqual(seen.count, 2, "the second copy of the same diagram is still a copy")
    }

    /// A concealed write is a password manager's. Nothing about it reaches the detector.
    func testConcealedContentIsNeverRead() {
        let board = makePasteboard()
        let monitor = ClipboardMonitor(pasteboard: board)
        var seen: [String] = []
        monitor.onMermaidCopied = { seen.append($0.text) }

        write(Self.diagram, to: board, markers: [PasteboardMarkers.concealed])
        monitor.poll()
        XCTAssertTrue(seen.isEmpty)
    }
}
